### PR TITLE
Fix issues when installing project dependencies on an Apple M1 machine (Fixes #140)

### LINKED ISSUE #140: Problems installing OTVision dependencies with pip on Apple M1

### PR DESCRIPTION
**Pull request by randy-seng**
on an Apple M1 machine (Fixes #140)

### CODE REVIEW

**Comment by frunika** [comment]
Just tried it, but doesn't work :'(

```log
ERROR: Could not find a version that satisfies the requirement torch==1.10.2 (from versions: 1.11.0)
ERROR: No matching distribution found for torch==1.10.2
```

**Comment by martinbaerwolff** [comment]
> Just tried it, but doesn't work :'(
> 
> ```
> ERROR: Could not find a version that satisfies the requirement torch==1.10.2 (from versions: 1.11.0)
> ERROR: No matching distribution found for torch==1.10.2
> ```
> 
> Could be a problem with python 3.10?!

At least on Windows I only provided requirements and tested it on Py 3.8 and 3.9. I guess some dependencies need a little time for upgrading to a new Py version.

**Review by frunika — APPROVED** [review]
nice, thanks :)

**Comment by frunika** [comment]
merge? :)

**Review by martinbaerwolff — APPROVED** [review]

**Pull request merged**
