### PR TITLE
Create detect.py to call yolov5/detect.py wit args

### PR DESCRIPTION
**Pull request by martinbaerwolff**

### CODE REVIEW

**Review by frunika — CHANGES_REQUESTED** [review]
Okay, you are constructing a command line call with python to call a python api through command line :D

It could be much easier to directly use the api by ultrasonic, couldn't it?

**Comment by martinbaerwolff** [comment]
> 
> 
> Okay, you are constructing a command line call with python to call a python api through command line :D
> 
> It could be much easier to directly use the api by ultrasonic, couldn't it?

Never heard of ultrasonic...goal for now was to not touch the code of yolov5. Can you give a link to ultrasonic? Did not find anything, just websites to measure distance with ultrasonic sensor on raspberry pi ^^

(Will change all of the "in code" comments on friday)

**Comment by frunika** [comment]
Whoops... Ultalytics ;)

Michael and me are working on a same problem for OTLabels. Let's talk these days about it.

**Comment by martinbaerwolff** [comment]
Closed

**Pull request closed without merging**
